# hatha ken y5adem delete 
#nelmio_cors:
 #   defaults:
  #      allow_credentials: false
   #     allow_origin: ['*']
    #    allow_headers: ['Content-Type', 'Authorization']
     #   allow_methods: ['GET', 'OPTIONS', 'DELETE', 'PUT', 'POST']
      #  max_age: 3600
    #paths:
     #   '^/': ~


#hathaa ta3 ines y5adem update 
#nelmio_cors:
 #   defaults:
  #      allow_credentials: false
   #     allow_origin: []
    #    allow_headers: []
     #   allow_methods: []
     #   expose_headers: []
      #  max_age: 0
       # hosts: []
      #  origin_regex: false
       # forced_allow_origin_value: ~
    # paths:
    #    '^/api/': # adjust the path according to your API's URL
     #       allow_origin: ['*'] # set allowed origins, or restrict to specific origins like ['http://example.com']
      #      allow_headers: ['*'] # set allowed headers, or restrict to specific headers
       #     allow_methods: ['POST', 'PUT' ,'GET', 'DELETE'] # set allowed HTTP methods, or restrict to specific methods
         #   max_age: 3600 # set the maximum age of preflight requests

 #min chatgpt
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/': # ajustez le chemin en fonction de l'URL de votre API
            allow_origin: ['*'] # autorise toutes les origines, ou restreignez à des origines spécifiques comme ['http://exemple.com']
            allow_headers: ['*'] # autorise tous les en-têtes, ou restreignez à des en-têtes spécifiques
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE'] # autorise les méthodes HTTP, y compris DELETE
            max_age: 3600 # définissez la durée maximale des requêtes préalables



#nelmio_cors:
#    defaults:
#        allow_credentials: false
#        allow_origin: []nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        max_age: 3600
#    paths:
#        '^/': null
#        allow_headers: []
#        allow_methods: []
#        expose_headers: []
#        max_age: 0
#        hosts: []
#        origin_regex: false
#        forced_allow_origin_value: ~
#        skip_same_as_origin: true
#    paths:
#        '^/api/':
#            allow_origin: ['*']
#            allow_headers: ['X-Custom-Auth']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: ['^http://localhost:[0-9]+']
#            allow_headers: ['X-Custom-Auth']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#            hosts: ['^api\.']





